### ISSUE TITLE
Why not push it to melpa? (update: mistake)

### ISSUE THREAD

**Issue by c02y** [emacsorphanage/popwin#120]
Why not push it to melpa so I can install it using package.el?

**update**: Sorry about this issue, I didn't find it in package-install window and didn't realize I already installed it, because it is required by guide-key package, but most importantly, you didn't mention in your README.md file that I can install from melpa using package.el, you really need to update your README.md file.

**Comment by jcs090218** [comment]
Readme file updated. See [here](https://github.com/emacsorphanage/popwin#melpa).
