### ISSUE TITLE
Package misc/* and submit them to Melpa?

### ISSUE THREAD

**Issue by wyuenho** [emacsorphanage/popwin#141]
I would like to submit the packages in `misc` to Melpa, but I'd have to modify the headers first.  @m2ym would you be open to this?

**Comment by jcs090218** [comment]
Hi, I’m new here. May I know why do you need to have misc opened? I mean if any other people having the same requests then I might agree with this. Otherwise if this is something personal I would have to say no. Thanks! :D

**Comment by wyuenho** [comment]
Because they are useful and common configuration for popwin but not available on Melpa? I mean, that's what they were originally written for right?

**Comment by jcs090218** [comment]
Hmmm, I see what you mean. I pretty much agree with you on opening the scripts in misc. I am actually not quite what will do to Melpa by opening or closing it. As I know this might cause the build time to Melpa yet I think we should still gain the benefits from Melpa in this case.

I think it would be fine if you make a PR there and see what they think? (They probably wouldn't bother anyway) :wink:

**Comment by wyuenho** [comment]
Too late for that now, this package has been out of maintenance for so long, I've already switched to https://github.com/bmag/emacs-purpose. It would be best to find another person to help you, or better yet, you can do it yourself.

**Comment by jcs090218** [comment]
Oh, okay. I will close this for now then. Thanks for letting me know! :D
