### ISSUE TITLE
Maintain issue.

### ISSUE THREAD

**Issue by jcs090218** [emacsorphanage/popwin#142]
@tarsius Is there anyone maintaining this package? I can help maintain this package! Give me the access if you think I can maintain It. Thanks! 😄

**Comment by tarsius** [comment]
Thanks for the offer! I've sent an invite.

**Comment by tarsius** [comment]
I've also revoked @iRi-E access from before the migration into this organization, as their only two commits are from eight years ago. That can be reverted if they want to get involved again of course.

**Comment by jcs090218** [comment]
Thanks! And thank you for the information! 👍
