### ISSUE TITLE
porblem with 2 sidebar windows

### ISSUE THREAD

**Issue by Junker** [emacsorphanage/popwin#145]
When emacs has 2 sidebar windows (neotree and ibuffer-sidebar) popwin works wrong, it duplicates main window.

**(window-tree) with 2 sidebar windows:**
without popwin: ```((nil (0 0 295 79) (t (0 0 37 79) #<window 93 on  *NeoTree*> #<window 125 on *:Buffers:*>) #<window 109 on 20_popwin.el>) #<window 4 on  *Minibuf-0*>)```
with popwin: ```((nil (0 0 295 79) (t (0 0 37 79) #<window 11 on  *NeoTree*> #<window 9 on *:Buffers:*>) (t (37 0 295 79) (nil ... #<window 17 on 20_popwin.el> #<window 23 on 20_popwin.el>) #<window 21 on *Help*>)) #<window 4 on  *Minibuf-0*>)```

**(window-tree) with 1 sidebar window:**
without popwin:```((nil (0 0 295 79) #<window 93 on  *NeoTree*> #<window 109 on 20_popwin.el>) #<window 4 on  *Minibuf-0*>)```
with popwin: ```((nil (0 0 295 79) #<window 11 on  *NeoTree*> (t (37 0 295 79) #<window 17 on 20_popwin.el> #<window 31 on *Help*>)) #<window 4 on  *Minibuf-0*>)```

- **emacs version:** GNU Emacs 28.0.50
- **popwin version:** popwin-20200908.816

**when 2 sidebar windows:**
![popwin_bad](https://user-images.githubusercontent.com/1144095/107844988-b7f5ce00-6e0a-11eb-81e6-8210a50b35a2.png)

**when 1 sidebar window:**
![popwin_good](https://user-images.githubusercontent.com/1144095/107844995-bf1cdc00-6e0a-11eb-8e61-38a848161ff5.png)

**Comment by jcs090218** [comment]
Close this now due to #146 is merged! :)
